### ISSUE TITLE
coverage tool is not generating correct report

### ISSUE THREAD

**Issue by supernovahs** [Layr-Labs/eigensdk-rs#114]
<img width="1323" alt="Screenshot 2024-09-13 at 3 26 30 PM" src="https://github.com/user-attachments/assets/f60e3601-21ac-4ca7-91fa-72fc573890dd">
<img width="1323" alt="Screenshot 2024-09-13 at 3 26 30 PM" src="https://github.com/user-attachments/assets/f60e3601-21ac-4ca7-91fa-72fc573890dd">
<img width="1081" alt="Screenshot 2024-09-13 at 3 26 12 PM" src="https://github.com/user-attachments/assets/8ea89d3d-e2cb-4291-9308-0e77d6ef924d">
<img width="1081" alt="Screenshot 2024-09-13 at 3 26 12 PM" src="https://github.com/user-attachments/assets/8ea89d3d-e2cb-4291-9308-0e77d6ef924d">

**Comment by TomasArrachea** [comment]
@supernovahs Are you still reporting this problem? I see that the [coverage on the CI](https://github.com/Layr-Labs/eigensdk-rs/actions/runs/10907020795/job/30269671601) is working fine, so I'm not sure what the problem is. Can you give more context?

**Comment by supernovahs** [comment]
its showing 0% test coverage  in example: prometheus and operators info memory,bls agg

**Comment by TomasArrachea** [comment]
I think we are getting different results. The problem could reside when generating the html report from the lcov.info file. We could change the CI so to directly upload the html result instead of the lcov.info dump to avoid this
