### ISSUE TITLE
Invalid signature revert/error when submitting task responses

### ISSUE THREAD

**Issue by Tjemmmic** [Layr-Labs/eigensdk-rs#142]
## Issue Summary
I have an Incredible Squaring AVS built using the eigensdk-rs. When submitting a Signed Task Response to a local testnet, I am getting a `signature is invalid` revert that comes from the BLSSignatureChecker.sol Smart Contract. The exact location of the revert can be found [here
](https://github.com/Layr-Labs/eigenlayer-middleware/blob/7d49b5181b09198ed275783453aa082bb3766990/src/BLSSignatureChecker.sol#L251)

```
    Transaction: 0x4dbea101548ef50beb687cb8d5f8eacba8264b5fc7e2c62abe11af0ec0faa889
    Gas used: 243678
    Error: reverted with: revert: BLSSignatureChecker.checkSignatures: signature is invalid

    Block Number: 213
    Block Hash: 0x23cb0c653f520c47929e4eb37f12cece55c2b0bf4c9ed41650a7a4eda4c114fc
    Block Time: \"Tue, 8 Oct 2024 22:21:31 +0000\"
```
---

## Steps to Reproduce
The context in which this error is happening is the following repository: https://github.com/webb-tools/gadget. We have an Incredible Squaring AVS, whose [task response submission](https://github.com/webb-tools/gadget/blob/8bb95973f1ea88a5dcf281eefef1b369034e16a1/blueprints/incredible-squaring-eigenlayer/src/lib.rs#L309) is the source of the error.

The steps found here can be followed to easily run the test that will reproduce the error: https://github.com/tangle-network/gadget/tree/fix-eigenlayer-example/blueprints/incredible-squaring-eigenlayer. You'll just need to:
 `git checkout fix-eigenlayer-example`

## Additional Context
- Using the eigensdk-rs, the signature seems to be valid. It succeeds the verification that occurs in the BLS Aggregator Service [here](https://github.com/Layr-Labs/eigensdk-rs/blob/667b3b3209d394d559a8c726546e3cb3e34cd3b3/crates/services/bls_aggregation/src/bls_agg.rs#L337).
- I have also tried validating the signature with the pairing [here](https://github.com/webb-tools/gadget/blob/78b24bf328f8f919007c1ec788ba55b0048d4278/blueprints/incredible-squaring-eigenlayer/src/lib.rs#L226), where it succeeds.

**Comment by supernovahs** [comment]
still getting the issue?

**Comment by Tjemmmic** [comment]
@supernovahs Solved, thanks!
